/**
 * Storefront "Scrolling Design" — an optional animated particle overlay a
 * seller can turn on for their storefront banner (golden stars drifting up,
 * confetti falling, etc). Stored as `Seller.scrollingDesign` (Json?):
 * `{ enabled: boolean, effect: ScrollingDesignKey }`.
 *
 * Deliberately a plain string key (like `cardDesign`/`cardFont` on Product —
 * see prisma/schema.prisma) rather than a fixed enum column, so new effects
 * can be added later without a migration. Unknown/missing keys just render
 * nothing (see ScrollingDesignOverlay.tsx) — never a broken storefront.
 */

export type ScrollingDesignDirection = "up" | "down" | "twinkle";
export type ScrollingDesignShape = "glyph" | "circle" | "rect" | "line";

export interface ScrollingDesignConfig {
  key: string;
  label: string;
  description: string;
  direction: ScrollingDesignDirection;
  shape: ScrollingDesignShape;
  /** Text/emoji rendered per particle — only used when shape is "glyph". */
  glyph?: string;
  /** Cycled across particles by index. */
  colors: string[];
  count: number;
  minSize: number;
  maxSize: number;
  minDuration: number;
  maxDuration: number;
  /** Falling shapes/glyphs also rotate as they fall (confetti, petals). */
  rotate?: boolean;
  /** Extra glow (box-shadow) — used for fireflies. */
  glow?: boolean;
}

export const SCROLLING_DESIGNS: ScrollingDesignConfig[] = [
  {
    key: "golden_stars",
    label: "Golden Stars",
    description: "Little gold stars drift up and fade — a warm, premium sparkle.",
    direction: "up",
    shape: "glyph",
    glyph: "✦",
    colors: ["#ffd700", "#ffc933", "#ffe066"],
    count: 16,
    minSize: 10,
    maxSize: 18,
    minDuration: 4,
    maxDuration: 7,
  },
  {
    key: "silver_sparkles",
    label: "Silver Sparkles",
    description: "Small silver-white sparkles twinkle in place across the banner.",
    direction: "twinkle",
    shape: "glyph",
    glyph: "✧",
    colors: ["#f8fafc", "#e2e8f0", "#cbd5e1"],
    count: 20,
    minSize: 8,
    maxSize: 14,
    minDuration: 1.6,
    maxDuration: 3,
  },
  {
    key: "confetti_party",
    label: "Confetti Party",
    description: "Colourful confetti tumbles down — festive and energetic.",
    direction: "down",
    shape: "rect",
    colors: ["#ef4444", "#f59e0b", "#22c55e", "#3b82f6", "#a855f7", "#ec4899"],
    count: 22,
    minSize: 6,
    maxSize: 10,
    minDuration: 3,
    maxDuration: 5,
    rotate: true,
  },
  {
    key: "gentle_snow",
    label: "Gentle Snow",
    description: "Soft snowflakes fall slowly — calm, wintery and clean.",
    direction: "down",
    shape: "glyph",
    glyph: "❄",
    colors: ["#ffffff", "#e0f2fe", "#bae6fd"],
    count: 18,
    minSize: 10,
    maxSize: 16,
    minDuration: 6,
    maxDuration: 10,
  },
  {
    key: "rising_bubbles",
    label: "Rising Bubbles",
    description: "Translucent bubbles float upward — light and playful.",
    direction: "up",
    shape: "circle",
    colors: ["rgba(125,211,252,0.55)", "rgba(191,219,254,0.5)", "rgba(224,242,254,0.6)"],
    count: 16,
    minSize: 8,
    maxSize: 20,
    minDuration: 5,
    maxDuration: 9,
  },
  {
    key: "floating_hearts",
    label: "Floating Hearts",
    description: "Little hearts drift upward — warm and romantic, great for gifting stores.",
    direction: "up",
    shape: "glyph",
    glyph: "♥",
    colors: ["#f43f5e", "#fb7185", "#fda4af"],
    count: 14,
    minSize: 10,
    maxSize: 18,
    minDuration: 4,
    maxDuration: 7,
  },
  {
    key: "magic_fireflies",
    label: "Magic Fireflies",
    description: "Tiny glowing fireflies twinkle softly — subtle and magical at night.",
    direction: "twinkle",
    shape: "circle",
    colors: ["#facc15", "#a3e635", "#fde047"],
    count: 14,
    minSize: 4,
    maxSize: 7,
    minDuration: 2,
    maxDuration: 4,
    glow: true,
  },
  {
    key: "falling_petals",
    label: "Falling Petals",
    description: "Pink petals flutter down, tumbling gently — soft and pretty.",
    direction: "down",
    shape: "glyph",
    glyph: "❀",
    colors: ["#f9a8d4", "#f472b6", "#fbcfe8"],
    count: 16,
    minSize: 12,
    maxSize: 18,
    minDuration: 5,
    maxDuration: 8,
    rotate: true,
  },
  {
    key: "party_balloons",
    label: "Party Balloons",
    description: "Balloons drift upward — bright and celebratory, great for sales.",
    direction: "up",
    shape: "glyph",
    glyph: "🎈",
    colors: ["#ffffff"],
    count: 10,
    minSize: 18,
    maxSize: 26,
    minDuration: 6,
    maxDuration: 10,
  },
  {
    key: "shimmer_rain",
    label: "Shimmer Rain",
    description: "Thin streaks of light rain down quickly — sleek and modern.",
    direction: "down",
    shape: "line",
    colors: ["rgba(191,219,254,0.85)", "rgba(224,242,254,0.7)", "rgba(255,255,255,0.6)"],
    count: 20,
    minSize: 14,
    maxSize: 26,
    minDuration: 1.2,
    maxDuration: 2.2,
  },
  {
    key: "rainbow_burst",
    label: "Rainbow Burst",
    description: "Vivid rainbow-coloured stars burst upward — loud, bright and fun.",
    direction: "up",
    shape: "glyph",
    glyph: "★",
    colors: ["#ef4444", "#f97316", "#eab308", "#22c55e", "#3b82f6", "#a855f7", "#ec4899"],
    count: 18,
    minSize: 10,
    maxSize: 18,
    minDuration: 3,
    maxDuration: 5,
  },
  {
    key: "neon_lightning",
    label: "Neon Lightning",
    description: "Electric bolts flash and fall fast — bright, bold and high-energy.",
    direction: "down",
    shape: "glyph",
    glyph: "⚡",
    colors: ["#facc15", "#38bdf8", "#f0abfc"],
    count: 12,
    minSize: 14,
    maxSize: 22,
    minDuration: 1,
    maxDuration: 1.8,
    glow: true,
  },
  {
    key: "ruby_flames",
    label: "Ruby Flames",
    description: "Bright flames flicker upward — bold, hot and eye-catching.",
    direction: "up",
    shape: "glyph",
    glyph: "🔥",
    colors: ["#ffffff"],
    count: 12,
    minSize: 14,
    maxSize: 22,
    minDuration: 2.5,
    maxDuration: 4,
    glow: true,
  },
  {
    key: "diamond_rain",
    label: "Diamond Rain",
    description: "Bright white-cyan diamonds fall and glitter — sharp, premium and sleek.",
    direction: "down",
    shape: "glyph",
    glyph: "◆",
    colors: ["#e0f2fe", "#a5f3fc", "#ffffff"],
    count: 16,
    minSize: 8,
    maxSize: 14,
    minDuration: 2,
    maxDuration: 3.5,
    rotate: true,
    glow: true,
  },
  {
    key: "electric_butterflies",
    label: "Electric Butterflies",
    description: "Bright pink and blue butterflies flutter upward — lively and eye-catching.",
    direction: "up",
    shape: "glyph",
    glyph: "🦋",
    colors: ["#ffffff"],
    count: 10,
    minSize: 16,
    maxSize: 24,
    minDuration: 4,
    maxDuration: 7,
  },
  {
    key: "money_rain",
    label: "Money Rain",
    description: "Gold coins tumble down — bold and celebratory, great for big sales and offers.",
    direction: "down",
    shape: "glyph",
    glyph: "💰",
    colors: ["#ffffff"],
    count: 12,
    minSize: 16,
    maxSize: 24,
    minDuration: 3,
    maxDuration: 5,
    rotate: true,
  },
  {
    key: "emerald_leaves",
    label: "Emerald Leaves",
    description: "Bright green leaves flutter down — fresh, natural and lively.",
    direction: "down",
    shape: "glyph",
    glyph: "🍃",
    colors: ["#ffffff"],
    count: 14,
    minSize: 14,
    maxSize: 20,
    minDuration: 4,
    maxDuration: 6.5,
    rotate: true,
  },
  {
    key: "aurora_lights",
    label: "Aurora Lights",
    description: "Bright glowing orbs of green, blue and violet drift slowly — dreamy and extraordinary.",
    direction: "up",
    shape: "circle",
    colors: ["#4ade80", "#38bdf8", "#a78bfa", "#f0abfc"],
    count: 12,
    minSize: 14,
    maxSize: 26,
    minDuration: 5,
    maxDuration: 8,
    glow: true,
  },
  {
    key: "galaxy_twinkle",
    label: "Galaxy Twinkle",
    description: "Deep violet stars twinkle like a night sky — dark, moody and striking.",
    direction: "twinkle",
    shape: "glyph",
    glyph: "✳",
    colors: ["#c4b5fd", "#818cf8", "#e9d5ff"],
    count: 20,
    minSize: 8,
    maxSize: 15,
    minDuration: 1.8,
    maxDuration: 3.2,
    glow: true,
  },
  {
    key: "shadow_mist",
    label: "Shadow Mist",
    description: "Dark smoky wisps drift upward and fade — moody, cinematic and extraordinary.",
    direction: "up",
    shape: "circle",
    colors: ["rgba(30,27,46,0.55)", "rgba(15,15,25,0.5)", "rgba(55,48,75,0.5)"],
    count: 10,
    minSize: 24,
    maxSize: 44,
    minDuration: 5,
    maxDuration: 8,
  },
];

export function getScrollingDesign(key: string | null | undefined): ScrollingDesignConfig | null {
  if (!key) return null;
  return SCROLLING_DESIGNS.find((d) => d.key === key) ?? null;
}
